name: cmp6230_test  # The environment name (you can change it)
channels:
  - defaults  # Channel where Conda will look for packages
  - conda-forge  # Optional: To get packages from the conda-forge channel
dependencies:
  - python=3.10  # Specify Python version (you can change it if you need)
  - pip  # Ensures pip is installed inside the Conda environment
  - pandas=1.5.3
  - numpy=1.24.4
  - scikit-learn=1.3.2
  - PyMySQL=1.1.2
  - great-expectations=0.18.12
  - xgboost=2.1.4
  - evidently=0.4.15
  - psycopg2=2.9.10
  - pip:
      - sqlalchemy==1.4.53  # Install this via pip (this matches your other environment)
      - pydantic==1.9.1    # Same for Pydantic
      - jupyter  # Installs Jupyter
      - fastapi  # FastAPI framework
      - uvicorn[standard]  # ASGI server for FastAPI
      - mlflow==2.4.0 # MLflow for model tracking
      - pyarrow==8.0.0  # For parquet files
      - matplotlib==3.7.2
      - seaborn==0.12.2
      - redis==5.0.0


